str="							&nbsp;&nbsp;&nbsp;&nbsp;随着中国电子商务的快速发展，购买{key}去淘宝网已经成为很多人的习惯，但是如何在淘宝中找到自己所需要的{key}？大海捞针去找{key}不是好办法，既费时又费力。";
str=str+"							<br />";
str=str+"							&nbsp;&nbsp;&nbsp;&nbsp;因此，通过淘宝{key}精品导航网站查找是个好方法，网站精选了当月淘宝上销量最多最好的{key}，能够快速达到您的需要。";
str=str+"						</div>";
str=str+"					</li >";
str=str+"					<li id=\"line-8\" class=\"widget-container widget_About\">";
str=str+"						<h2 class=\"widget-title\"><img src=\"/templets/fusee_cizgi.jpg\" width=\"247\" height=\"1\" /></h2>";
str=str+"						<div id=\"Line_wrap\"></div>";
str=str+"					</li >";
str=str+"					<li id=\"contact-6\" class=\"widget-container widget_text\">";
str=str+"						<h2 class=\"widget-title\"><img src=\"/templets/contact.png\" width=\"53\" height=\"18\" /></h2>";
str=str+"					</li >";
str=str+"					<li id=\"dictionary-4\" class=\"widget-container widget_dictionary\">";
str=str+"						<div class=\"textwidget\">";
str=str+"							<span class=\"STYLE2\">1.为什么要做这样的网站？</span><br>";
str=str+"								&nbsp;&nbsp;&nbsp;&nbsp;能够增加用户体验，淘宝{key}精品导航站展示的所有相关{key}的商品都是当月淘宝销量最多最好的，可以让用户可以立刻找到自己所需要的{key}，节省用户在淘宝上寻找{key}所需的大量时间。同时为商家扩宽销售宣传{key}的门路。";
str=str+"								<br />";
str=str+"							<span class=\"STYLE2\"><strong>2.</strong>淘宝{key}精品站不会是购物陷阱或者绑定病毒木马的网站吧？</span><br>";
str=str+"								&nbsp;&nbsp;&nbsp;&nbsp;淘宝{key}精品导航站郑重承诺：";
str=str+"								<br />";
str=str+"								<span class=\"entry-utility-prep-cat-links\">网站绝对不会是购物陷阱或者绑定任何病毒木马，大家可以看到我们所有展示的{key}相关商品都是来自淘宝官方网站，只是一个引导消费者购物的导航站，请用户放心使用。</span>";
str=str+"								<br />";
str=str+"							<span class=\"STYLE2\"><strong>3.</strong>没有我需要的{key}相关商品，怎么办？</span>";
str=str+"							<br />";
str=str.replace(/{key}/g,a);
document.writeln(str);