document.writeln("<script type=\"text/javascript\">");
document.writeln("alimama_pid=\"mm_15557716_2645240_9629294\";");
document.writeln("alimama_type=\"g\";");
document.writeln("alimama_tks={};");
document.writeln("alimama_tks.style_i=3;");
document.writeln("alimama_tks.lg_i=1;");
document.writeln("alimama_tks.w_i=\"550\";");
document.writeln("alimama_tks.h_i=95;");
document.writeln("alimama_tks.btn_i=1;");
document.writeln("alimama_tks.txt_s=\"aaa\";");
document.writeln("alimama_tks.hot_i=1;");
document.writeln("alimama_tks.hc_c=\"0065FF\";");
document.writeln("alimama_tks.c_i=1;");
document.writeln("alimama_tks.kwdcat_s=\"all\";");
document.writeln("alimama_tks.bk_i=1;");
document.writeln("alimama_tks.bkc_c=\"EEEEEE\";");
document.writeln("alimama_tks.sb_i=1;");
document.writeln("alimama_tks.sbpos_s=\"t\";");
document.writeln("alimama_tks.kwdfnt_s=\"12px\";");
document.writeln("alimama_tks.kwdln_i=2;");
document.writeln("alimama_tks.sbbgc_c=\"FFFFFF\";");
document.writeln("</script>");
document.writeln("<script type=\"text/javascript\" src=\"http://a.alimama.cn/inf.js\"></script>");